### ISSUE TITLE
command 'magit.status' not found

### ISSUE THREAD

**Issue by RasmusWL** [kahole/vscode-magit#238] opened 2022-12-08 10:37 UTC
I sometimes get this when trying to open the magit status view. If I run the `Magit status` command, I currently get the following message :disappointed: 

![image](https://user-images.githubusercontent.com/1054041/206425003-f3d537b8-797e-4e61-a022-422e6cafb608.png)

I couldn't see any logs in the outputs I checked, so let me know if there is somewhere specific I should be looking, and I can be sure to grap some logs for you to look at :blush:

**Comment by kahole** [comment] 2022-12-08 10:54
I think I know how to reproduce this.
It happens when you run magit status quickly after opening a "project" / vscode window.

Something isnt right with the activation of the extension. It's only supposed to activate on first use, which it does, but it seems like it fails if activation is attempted too soon. Maybe some dependency isnt properly awaited

**Comment by jacobemcken** [comment] 2022-12-12 06:54
> It happens when you run magit status quickly after opening a "project" / vscode window.

I can confirm that I have the same experience.

**Comment by jml** [comment] 2022-12-16 12:19
Same. To work around the issue, I run the "Developer: Reload Window" command.

**Comment by kahole** [comment] 2023-03-01 09:42
The cause of this is that vscode loads it's internal git extension "onStartupFinished" or similar. The internal git extension is a dependency of `edamagit`, thus any activation of `edamagit` before the internal git extension has loaded will fail.

If we could somehow activate the internal git extension when activating `edamagit`, or the opposite; wait until startup has completed to allow activation of `edamagit` this would go away.

**Comment by kahole** [comment] 2023-03-02 09:28
I have implemented a check-and-wait for the internal git extension, together with a "sleep" to allow it to load some state. This eliminates the error at least, and should load the edamagit status buffer correctly, given that the internal git extension has had enough time to load it's state. Closing this issue

**Closed as completed by kahole** 2023-03-02 09:28 UTC
