### ISSUE TITLE
Magit status opening to other column when display-buffer-function is set to same-column

### ISSUE THREAD

**Issue by Mappless** [kahole/vscode-magit#258] opened 2023-05-23 07:27 UTC
I noticed since version `0.6.41`, the Magit status view open to an other column despite having `"magit.display-buffer-function": "same-column"` in the settings.

**Comment by kahole** [comment] 2023-05-23 11:27
Addressed in 2bca719144f79f6f7ee39fcd55dcf85a71c1a4e4
Version 0.6.42.
Seems like you had to have an active column after the last refactor. Hopefully this fixes it. I was actually not able to reproduce your issue.

**Closed as completed by kahole** 2023-05-23 11:27 UTC
